id = "basilisk"
name = "Basilisk C"
version = "0.2.5"
schema_version = 1
authors = ["Zed Basilisk Contributors"]
description = "Basilisk C language support powered by qcc-lsp"
repository = "https://github.com/VatsalSy/zed-qcc"
languages = ["languages/basilisk"]

[language_servers.qcc-lsp]
name = "qcc-lsp"
languages = ["Basilisk C", "C"]

[language_servers.qcc-lsp.language_ids]
"Basilisk C" = "basilisk"
"C" = "basilisk"

[[capabilities]]
kind = "npm:install"
package = "vscode-languageserver"

[[capabilities]]
kind = "npm:install"
package = "vscode-languageserver-textdocument"

[[capabilities]]
kind = "npm:install"
package = "vscode-uri"
